namespace IzbanKiosk.Domain
{
    public enum KioskTransactionState
    {
        Created,
        CardDetected,
        CardValidated,
        BalanceQueryPending,
        BalanceVerified,
        BalanceQueryFailed,
        AmountSelected,
        PreAuthorizationPending,
        PreAuthorized,
        PaymentPending,
        PaymentOutcomeUnknown,
        PaymentDeclined,
        PaymentCancelled,
        PaymentApproved,
        LoadPending,
        LoadOutcomeUnknown,
        LoadVerificationPending,
        LoadVerified,
        LoadVerificationFailed,
        CapturePending,
        CaptureOutcomeUnknown,
        Captured,
        CaptureFailed,
        ReversalPending,
        Reversed,
        ReversalFailed,
        Completed,
        Failed,
        ManualReview
    }
}
